notifications:
  email: false

branches:
  only:
    - master

language: go

go:
  - "1.12.x"

install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
